# Menu Principal
[[main]]
  name = "Guia Iniciante"
  pageRef = "guia-iniciante"
  weight = 10

[[main]]
  name = "Campanha"
  pageRef = "campanha"
  weight = 20

[[main]]
  name = "Raças"
  pageRef = "racas"
  weight = 30

[[main]]
  name = "Personagens"
  pageRef = "personagens"
  weight = 40

[[main]]
  name = "Facções"
  pageRef = "faccoes"
  weight = 50

[[main]]
  name = "Criaturas"
  pageRef = "criaturas"
  weight = 60

[[main]]
  name = "Mundo"
  pageRef = "mundo"
  weight = 70

[[main]]
  name = "Regiões"
  pageRef = "regioes"
  weight = 80

# Dropdowns dos Menus
[[main]]
  name = "Anões"
  parent = "Raças"
  pageRef = "anoes"
  weight = 20

[[main]]
  name = "Humanos"
  parent = "Raças"
  pageRef = "humanos"
  weight = 21

[[main]]
  name = "Elfos"
  parent = "Raças"
  pageRef = "elfos"
  weight = 22

[[main]]
  name = "A Carta"
  parent = "Facções"
  pageRef = "carta"
  weight = 30

[[main]]
  name = "Darkspawn"
  parent = "Criaturas"
  pageRef = "darkspawn"
  weight = 60

# Footer
[[footer]]
  name = "Glossário"
  pageRef = "mundo/glossario"
  weight = 10

[[footer]]
  name = "Regras"
  pageRef = "regras"
  weight = 20