# Menu Principal
[[main]]
  name = "Guia Iniciante"
  pageRef = "guia-iniciante"
  weight = 10

[[main]]
  name = "Campanha"
  pageRef = "campanha"
  weight = 20

[[main]]
  name = "Raças"
  pageRef = "racas"
  weight = 30

[[main]]
  name = "Personagens"
  pageRef = "personagens"
  weight = 40

[[main]]
  name = "Facções"
  pageRef = "faccoes"
  weight = 50

[[main]]
  name = "Criaturas"
  pageRef = "criaturas"
  weight = 60

[[main]]
  name = "Mundo"
  pageRef = "mundo"
  weight = 70

[[main]]
  name = "Regiões"
  pageRef = "regioes"
  weight = 80

# Submenu de Navegação
[[subnavigation]]
  name = "Darkspawn"
  pageRef = "criaturas/darkspawn"
  weight = 10

[[subnavigation]]
  name = "Anões"
  pageRef = "racas/anoes"
  weight = 20

[[subnavigation]]
  name = "Humanos"
  pageRef = "racas/humanos"
  weight = 21

[[subnavigation]]
  name = "Elfos"
  pageRef = "racas/elfos"
  weight = 22

[[subnavigation]]
  name = "A Carta"
  pageRef = "faccoes/carta"
  weight = 30

# Footer
[[footer]]
  name = "Glossário"
  pageRef = "mundo/glossario"
  weight = 10

[[footer]]
  name = "Regras"
  pageRef = "regras"
  weight = 20